# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(verbose_name='経度'),
        ),
    ]
